### ISSUE TITLE
Unable to Import OSMOSIS

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#210]
On the import Osmosis screen the balance is not loading and the following errors are being displayed in the console:

index.de15b10a.js:27 POST https://rpc-osmosis.keplr.app/ net::ERR_ABORTED 404

index.de15b10a.js:27 POST https://rpc-osmosis.keplr.app/ 404

useAsyncData error Error: Bad status on response: 404
    at filterBadStatus (index.de15b10a.js:27:512274)
    at async HttpClient.execute (index.de15b10a.js:27:512760)
    at async Function.detectVersion (index.de15b10a.js:27:556021)
    at async Function.create (index.de15b10a.js:27:555871)
    at async KeplrWalletProvider.getQueryClient (index.de15b10a.js:68:22266)
    at async KeplrWalletProvider.fetchBalances (index.de15b10a.js:68:24827)
    at async Object.updateBalances (index.de15b10a.js:409:232895)

index.de15b10a.js:27 Uncaught (in promise) Error: Bad status on response: 404
    at filterBadStatus (index.de15b10a.js:27:512274)
    at async HttpClient.execute (index.de15b10a.js:27:512760)
    at async Function.detectVersion (index.de15b10a.js:27:556021)
    at async Function.create (index.de15b10a.js:27:555871)
    at async KeplrWalletProvider.getQueryClient (index.de15b10a.js:68:22266)
    at async KeplrWalletProvider.fetchBalances (index.de15b10a.js:68:24827)
    at async Object.updateBalances (index.de15b10a.js:409:232895)

<img width="1675" alt="Screenshot 2022-01-18 at 10 38 49 AM" src="https://user-images.githubusercontent.com/1245772/149969397-4a0c55e3-8e7a-4fbf-866c-08c5231ed0e9.png">

**Comment by ajoslin** [comment]
Fixed via https://github.com/sifchain/sifchain-ui/commit/df3c0abbeadb312f9996d42cb5c732828ea7ba29

Some of our RPC configs were still pointing at Keplr.
