### ISSUE TITLE
Unable to import Osmos to Sifchain

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#236]
The following error is being returned in the console:

index.11aec7e6.js:494 Error: Received ill-formatted txhash. Must be non-empty upper-case hex
    at KeplrWalletProvider.broadcast (index.11aec7e6.js:77:153968)
    at async IBCService.bridgeTokens (index.11aec7e6.js:35:18246)
    at async IBCService.transfer (index.11aec7e6.js:35:18785)
    at async Object.transfer (index.11aec7e6.js:402:176922)
    at async runTransfer (index.11aec7e6.js:451:112001)

![image](https://user-images.githubusercontent.com/1245772/152657434-8589f457-37a2-4959-a24b-e1294df6eff7.png)

**Comment by sifmoon** [comment]
Additional details:

Direct IBC of ROWAN to/from Osmosis - works.  
Direct IBC of OSMO to/from Sifchain - works.  
|Deposit ROWAN on Osmosis UI - works.  
Deposit OSMO on Sifchain UI - no worky.

**Comment by emperorjm** [comment]
This has since been resolved.
