### ISSUE TITLE
Unable to import LUNA due to insufficient funds error

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/Support-Tickets#350]
Getting an error "You have insufficient funds" when trying to import 20 LIUNA with a balance of 31.

**Console error:**

ror: 0uusd is smaller than 19785uusd: insufficient funds: insufficient funds
    at toExplicitError (index.290dd98d.js:310:613)
    at Array.<anonymous> (index.290dd98d.js:310:1128)
    at tt.<anonymous> (index.290dd98d.js:156:151519)
    at tt.EventEmitter$8.emit (index.290dd98d.js:23:358114)
    at addChunk (index.290dd98d.js:156:120591)
    at readableAddChunk (index.290dd98d.js:156:120375)
    at tt.Readable.push (index.290dd98d.js:156:119559)
    at tt._onMessage (index.290dd98d.js:156:148260)
console.error @ index.290dd98d.js:405
bridgeTokens @ index.290dd98d.js:133
await in bridgeTokens (async)
transfer @ index.290dd98d.js:133
transfer @ index.290dd98d.js:310
runTransfer @ index.290dd98d.js:366
await in runTransfer (async)
runImport @ index.290dd98d.js:366
(anonymous) @ index.290dd98d.js:310
(anonymous) @ index.290dd98d.js:370
et @ index.290dd98d.js:370
dispatch @ index.290dd98d.js:370
(anonymous) @ index.290dd98d.js:310
runImport @ index.290dd98d.js:370
onClick @ index.290dd98d.js:382
callWithErrorHandling @ index.290dd98d.js:6
callWithAsyncErrorHandling @ index.290dd98d.js:6
nt @ index.290dd98d.js:6
index.290dd98d.js:133 {responses: Array(1)}
index.290dd98d.js:133 {txFailure.rawLog: '0uusd is smaller than 19785uusd: insufficient funds: insufficient funds'}

<img width="1512" alt="Screenshot 2022-05-11 at 8 26 31 AM" src="https://user-images.githubusercontent.com/1245772/167860990-15cfbfff-187a-436a-a92f-bf46299c1f84.png">

![Sifchain](https://user-images.githubusercontent.com/1245772/167861242-81a26581-1422-43e5-924b-39250d41b9a1.png)

![image](https://user-images.githubusercontent.com/1245772/167860397-1b8d61be-c263-4f9a-a0fc-9bd1e8796cf6.png)

**Comment by emperorjm** [comment]
UST is also required to complete the import.
