### ISSUE TITLE
Pool page not loading

### ISSUE THREAD

**Issue by lufa23** [Sifchain/Support-Tickets#392]
**Describe the bug**

Pool page not loading

**How to Reproduce**

1. Connect Keplr
2. Go to https://sifchain.akash.pro/#/pool

**Error logs**
```
index.8990e276.js:23 Error: Cannot render environment null undefined
    at getEnv (index.8990e276.js:23:160239)
    at index.8990e276.js:319:24757
    at index.8990e276.js:1:700
    at index.8990e276.js:414:22119
```

**Screenshots**

<img width="1424" alt="Screenshot 2022-06-14 at 00 04 01" src="https://user-images.githubusercontent.com/67415638/173452857-19ee0ae7-116f-46a1-949e-8173ebcdeef4.png">

**Providing as much detail as possible will help engineers to solve the case faster..**

Thanks!

**Comment by lufa23** [comment]
Pool page working for RedStarling and Forbole. Not working for Akash and Consensus One. Teams have been contacted

**Comment by lufa23** [comment]
clearing cache works
